# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "nvme" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/74e1cce8-d985-4efb-8f9f-f6200d903505";
      fsType = "btrfs";
      options = ["subvol=root"];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/74e1cce8-d985-4efb-8f9f-f6200d903505";
      fsType = "btrfs";
      options = ["subvol=home"];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/74e1cce8-d985-4efb-8f9f-f6200d903505";
      fsType = "btrfs";
      options = ["subvol=nix"];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/2BB7-203E";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/2623c27d-d562-4037-be57-f1ccb2d54aa8"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
