{...}: {
  # Raise the open-files limit system-wide. Generated by nix-darwin so the
  # plist is always well-formed; verify with `launchctl limit maxfiles`.
  launchd.daemons.limit-maxfiles = {
    serviceConfig = {
      Label = "limit.maxfiles";
      ProgramArguments = [
        "launchctl"
        "limit"
        "maxfiles"
        "524288"
        "524288"
      ];
      RunAtLoad = true;
    };
  };
}
